chromeos-base/libhwsec: Add missing dep
    FAILED: obj/libhwsec/backend/tpm2/hardware_abstraction_internal_library.u2f.o
    ../../../../../../../../../mnt/host/source/src/platform2/libhwsec/backend/tpm2/u2f.cc:16:10: fatal error: 'trunks/cr50_headers/u2f.h' file not found
    #include <trunks/cr50_headers/u2f.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    [33/75] CXX obj/gen/include/libhwsec

BUG=b:262460834
TEST=BOARD=amd64-generic bazel build --//bazel/sdk:new-sdk @portage//chromeos-base/libhwsec

Change-Id: I4ce789265eeba1bbec626806c00a88bf0782bf9d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4424037
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>