chromeos-base/ml-cmdline: add missing dependencies
Adding chromeos-base/system_api to fix:
Command: /usr/bin/env /build/amd64-generic/tmp/portage/chromeos-base/ml-cmdline-9999/work/ml-cmdline-9999/platform2/common-mk/pkg-config_wrapper.py /build/amd64-generic/build/bin/pkg-config libbrillo libchrome libmetrics libminijail libmojo system_api zlib
Returned 1.
stderr:

Package system_api was not found in the pkg-config search path.
Perhaps you should add the directory containing `system_api.pc'
to the PKG_CONFIG_PATH environment variable
No package 'system_api' found

Adding dev-libs/marisa-aosp to fix:
/build/amd64-generic/usr/include/libtextclassifier/annotator/vocab/vocab-level-table.h:22:10: fatal error: 'marisa-aosp/marisa/trie.h' file not found
 #include "marisa-aosp/marisa/trie.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Adding dev-libs/libutf to fix:
ld.lld: error: unable to find library -lutf

BUG=b:273158812
TEST=BOARD=amd64-generic bazel build @portage//chromeos-base/ml-cmdline

Original-Change-Id: Ica9d09a9742dcdca1bdb74511efcbe390945fe1f
Original-Reviewed-on: https://team-review.git.corp.google.com/c/cros-build-tiger/third_party/chromiumos-overlay/+/1795530
Original-Reviewed-by: Shuhei Takahashi <nya@google.com>
Original-Reviewed-by: Ryo Hashimoto <hashimoto@google.com>
(cherry picked from commit 905952d4659fdeff755da311cd92c5d8979ec963)

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//chromeos-base/ml-cmdline

Change-Id: Ibd0b7c1088c81de9ae327fe5c7c5d13970917d82
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4410051
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>