chromeos-base/libiioservice_ipc: Add missing depend
../../../../../../../../../mnt/host/source/src/platform2/iioservice/libiioservice_ipc/sensor_client_dbus.cc:11:10: fatal error: 'chromeos/dbus/service_constants.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original-Change-Id: I3719cb2f84d3ebafc7c0de0668c5dcdf2d0a5d07
Original-Reviewed-on: https://team-review.git.corp.google.com/c/cros-build-tiger/third_party/chromiumos-overlay/+/1624015
Original-Reviewed-by: Shuhei Takahashi <nya@google.com>
(cherry picked from commit 3ce73b06f20371bf4f2702d32a446e52ac6db014)

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build  --//bazel/sdk:new-sdk @portage//virtual/target-os:all

Change-Id: Iee1234ad8dc1067588497447649b7f21ba8c87e4
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4338053
Reviewed-by: Shuhei Takahashi <nya@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>