chromeos-base/u2fd-client: Add missing dep
    ../../../../../../../../../mnt/host/source/src/platform2/u2fd/client/u2f_apdu.cc:14:10: fatal error: 'trunks/cr50_headers/u2f.h' file not found
    #include <trunks/cr50_headers/u2f.h>
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//chromeos-base/u2fd-client

Change-Id: Ic5246d8551864870d10a0f3d2219f3d57dfce766
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4371240
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>