dev-rust/textwrap: fix dependency versions
The textwrap crate declares exact version requirements for its
dependencies. In particular, it requires hyphenation-0.7.1, but if
a newer version of hyphenation is added to the tree, Portage would pick
the newer version and then textwrap would consider its dependency to be
unsatisfied:

    19:01:47 >>> Install dev-rust/textwrap-0.11.0 into /build/amd64-generic/tmp/portage/dev-rust/textwrap-0.11.0/image/
       Packaging textwrap v0.11.0 (/build/amd64-generic/tmp/portage/dev-rust/textwrap-0.11.0/work/textwrap-0.11.0)
       Archiving Cargo.lock
    error: failed to prepare local package for uploading

    Caused by:
      failed to select a version for the requirement `hyphenation = "^0.7.1"`
      candidate versions found which didn't match: 0.8.0

Found in this patch, which tries to add hyphenation-0.8.0:
https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/3076229

BUG=chromium:1225099
TEST=add dev-rust/hyphenation-0.8.0, then: emerge dev-rust/textwrap

Change-Id: Id65f502bf3e8e857166ad954981c83692cb3bf84
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/3096822
Tested-by: Dan Callaghan <dcallagh@chromium.org>
Reviewed-by: Peter Marheine <pmarheine@chromium.org>
Reviewed-by: Edward O'Callaghan <quasisec@chromium.org>
Commit-Queue: Dan Callaghan <dcallagh@chromium.org>