chromeos-base/hps-firmware: update version dependency for bitflags
Since commit dc99ceb6 hps-firmware requires bitflags >= 1.3.2, so
declare that in the ebuild.

Fixes a failure which can happen in existing chroots where older
bitflags is still installed:

    error: failed to select a version for the requirement `bitflags = "^1.3.2"`
    candidate versions found which didn't match: 1.2.1

BUG=none
TEST=emerge-brya hps-firmware

Change-Id: I767dca77175a076aae4fbe2d4f1a007c07c02edb
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/3273832
Tested-by: Dan Callaghan <dcallagh@chromium.org>
Reviewed-by: David Lattimore <dml@chromium.org>
Commit-Queue: Dan Callaghan <dcallagh@chromium.org>