media-libs/cros-camera-libcamera_connector_test: Add missing dep
    In file included from ../../../../../../../../../mnt/host/source/src/platform2/camera/common/libcamera_connector_test/gtest_main.cc:31:
    In file included from ../../../../../../../../../mnt/host/source/src/platform2/camera/common/libcamera_connector_test/i420_buffer.h:17:
    ../../../../../../../../../mnt/host/source/src/platform2/camera/common/libcamera_connector_test/util.h:14:10: fatal error: 'cros-camera/camera_service_connector.h' file not found
    #include "cros-camera/camera_service_connector.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//media-libs/cros-camera-libcamera_connector_test

Change-Id: Ib5fb95ebd03a3b0dfa2b9bb654e82b1f85191449
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4410101
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>