libchrome: Disable warning -Wrange-loop-analysis
The new warning in llvm-next compiler breaks libchrome package.
Since the issue in not severe disable the warning to unblock the
llvm-next builds.

Fixed the following failure:
libchrome-462023-r50: malloc_dump_provider.cc:304:28: error: loop
variable 'alloc_size' is always a copy because the range of type
'base::trace_event::AllocationRegister' does not return a reference
[-Werror,-Wrange-loop-analysis]
libchrome-462023-r50:for (const auto& alloc_size : *allocation_register_) {
libchrome-462023-r50:                 ^
libchrome-462023-r50: malloc_dump_provider.cc:304:16: note: use
non-reference type 'base::trace_event::AllocationRegister::Allocation'
libchrome-462023-r50: for (const auto& alloc_size : *allocation_register_) {
libchrome-462023-r50:      ^~~~~~~~~~~~~~~~~~~~~~~~
libchrome-462023-r50: 1 error generated.

BUG=chromium:1041757
TEST=emerge-kevin libchrome

Change-Id: Ibc8201882069817fa63370333531dcd19f9c6767
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/2006543
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Denis Nikitin <denik@chromium.org>