chromeos-base/cros-camera: Add missing dep
    FAILED: obj/camera/hal_adapter/cros_camera_service.camera_hal_adapter.o
    In file included from ../../../../../../../../../mnt/host/source/src/platform2/camera/hal_adapter/camera_hal_adapter.cc:7:
    In file included from ../../../../../../../../../mnt/host/source/src/platform2/camera/hal_adapter/camera_hal_adapter.h:30:
    In file included from ../../../../../../../../../mnt/host/source/src/platform2/camera/common/stream_manipulator.h:29:
    In file included from ../../../../../../../../../mnt/host/source/src/platform2/camera/gpu/gpu_resources.h:25:
    ../../../../../../../../../mnt/host/source/src/platform2/camera/gpu/egl/egl_context.h:13:10: fatal error: 'EGL/eglplatform.h' file not found
    #include <EGL/eglplatform.h>
             ^~~~~~~~~~~~~~~~~~~
    1 error generated.

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build  --//bazel/sdk:new-sdk @portage//chromeos-base/cros-camera

Change-Id: I2c65fe63f47ae03b56a0f415f59c13db755fdf3d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4364481
Reviewed-by: Ricky Liang <jcliang@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>