media-libs/cros-camera-frame-annotator: Add missing dep
    In file included from ../../../../../../../../../mnt/host/source/src/platform2/camera/gpu/egl/egl_fence.cc:7:
    ../../../../../../../../../mnt/host/source/src/platform2/camera/gpu/egl/egl_fence.h:11:10: fatal error: 'EGL/egl.h' file not found
    #include <EGL/egl.h>
             ^~~~~~~~~~~
    1 error generated.
    ninja: build stopped: subcommand failed.

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//chromeos-base/cros-camera-frame-annotator

Change-Id: Ifb65ab97e8cbcb295bd9d3dce8f647742e7eba60
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4410059
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>