chromeos-base/crash-reporter: Add missing DEPEND
keyutils is also needed as a DEPEND.

    ../../../../../../../../../mnt/host/source/src/platform2/crash-reporter/util.cc:19:10: fatal error: 'keyutils.h' file not found
    #include <keyutils.h>
             ^~~~~~~~~~~~
    1 error generated.

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build  --//bazel/sdk:new-sdk @portage//chromeos-base/crash-reporter

Change-Id: Ie52e4964d945df6d62b94ed064861bf04ea5ef1e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4364252
Reviewed-by: Miriam Zimmerman <mutexlox@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>