Allow -n for no-op/dry run operation
When -n is passed, the script will verify that the SN Bits are
properly set, and issue a non-error message if so, as well as exit
with a 0 code. RMAed devices will also produce a warning rather than
an errot. Other errors are unchanged.

See example invocations below (with $ representing the prompt). These
start with an ideal machine with no BoardID or SN Bits written for
illustration purposes (e.g. a factory situation).

$ vpd -s attested_device_id=7627G002E3
$ /usr/share/cros/cr50-set-sn-bits.sh -n
SN Bits have not been set yet.
$ echo $?
0
$ /usr/share/cros/cr50-set-sn-bits.sh
Successfully updated SN Bits for 7627G002E3.
$ echo $?
0
$ /usr/share/cros/cr50-set-sn-bits.sh -n
SN Bits have properly been set.
$ echo $?
0
$ vpd -s attested_device_id=OOPS
$ /usr/share/cros/cr50-set-sn-bits.sh -n
ERROR: SN Bits have been set differently (8eecee3da879603e9558c987 vs 5f66a65b6ac5c1c8415ed15b).
$ echo $?
3
$

If a device has been RMAed (as indicated in the RMA portion of RMA + SN
Bits), a warning will be printed, e.g.

$ /usr/share/cros/cr50-set-sn-bits.sh -n
WARNING: This device has been RMAed, preventing changes to SN Bits.
SN Bits have properly been set.
$

BUG=b:156438336
TEST=See above

Change-Id: I121092d544a30000a5017244ea8c6daa1e150706
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/2186531
Tested-by: Yves Arrouye <drcrash@chromium.org>
Reviewed-by: Stimim Chen <stimim@chromium.org>
Commit-Queue: Yves Arrouye <drcrash@chromium.org>