chromeos-base/drm-tests: add missing dependencies
Adding dev-libs/openssl for:
/build/amd64-generic/tmp/portage/chromeos-base/drm-tests-9999/work/drm-tests-9999/v4l2_stateful_decoder.c:15:10: fatal error:
      'openssl/md5.h' file not found
         ^~~~~~~~~~~~~~~

Adding dev-util/vulkan-headers for:
/build/amd64-generic/tmp/portage/chromeos-base/drm-tests-9999/work/drm-tests-9999/vk_glow.c:13:10: fatal error:
      'vulkan/vulkan.h' file not found
         ^~~~~~~~~~~~~~~~~

BUG=b:273158812
TEST=BOARD=amd64-generic bazel build @portage//chromeos-base/drm-tests

Original-Change-Id: I36d9d86492c5d45f47698951b8c9cdfe43114764
Original-Reviewed-on: https://team-review.git.corp.google.com/c/cros-build-tiger/third_party/chromiumos-overlay/+/1789898
Original-Reviewed-by: Shuhei Takahashi <nya@google.com>
(cherry picked from commit aece9fb0137e59ce45c01f072bf518e37c7cc89c)

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//chromeos-base/drm-tests

Change-Id: I85d1f8f7a566d38fee19fd731f9a40d875e3fb6d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4410047
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>