ml: add absl as a dependency for tensorflow uprev
This is to simplify the chain of CL's for the tensorflow uprev. No harm
in adding this dependency idependently since the uprev is imminent.

When TFLite is uprev'd, ml will fail to build without this dep:
delegates/nnapi/nnapi_delegate.h:23:10: fatal error: \
'absl/types/optional.h' file not found

BUG=b:158258086
TEST=FEATURES=test emerge-{betty,octopus,kukui} chromeos-base/ml \
                                                chromeos-base/ml-cmdline

Change-Id: Ide192953768f7f7e95a52b3d22a358add8f0938b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/2275762
Tested-by: Jim Pollock <jmpollock@chromium.org>
Reviewed-by: Stuart Langley <slangley@chromium.org>
Commit-Queue: Jim Pollock <jmpollock@chromium.org>
Auto-Submit: Jim Pollock <jmpollock@chromium.org>