chromeos-base/libec: Add RDEPEND deps
We need these so that the deps are available to things that link against
this library:

In file included from ../../../../../../../../../mnt/host/source/src/platform2/rgbkbd/internal_rgb_keyboard.h:13:
../../../../../../../../../mnt/host/source/src/platform2/libec/ec_command.h:19:10: fatal error: 'chromeos/ec/cros_ec_dev.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Package libpower_manager-client was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpower_manager-client.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpower_manager-client', required by 'libec', not found

Original-Change-Id: Ifa959bab2bf9c446e0d96282ecec081ca124b732
Original-Reviewed-on: https://team-review.git.corp.google.com/c/cros-build-tiger/third_party/chromiumos-overlay/+/1624023
Original-Reviewed-by: Shuhei Takahashi <nya@google.com>

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build  --//bazel/sdk:new-sdk @portage//virtual/target-os:all

Change-Id: I66f81961697940582e2ac610e7f8065f43c0ed36
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4338784
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Shuhei Takahashi <nya@chromium.org>