dev-python/python-uinput: Add missing dep
ld.lld: error: unable to find library -lpython3.6m
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'aarch64-cros-linux-gnu-clang' failed with exit status 1
 * ERROR: dev-python/python-uinput-0.11.2-r5::chromiumos failed (compile phase):

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//dev-python/python-uinput

Change-Id: I05846f55db02acde4f0ed0705aca0bf9c38f56dc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4410055
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>