compiler-rt: Fix symlink.
The symlink was invalid causing the following error in
master-paladin:
>     raise AssertionError("ebuild not found for '%s%s%s'" % (cpv, _repo_separator, repo.name))
> AssertionError: ebuild not found for 'sys-libs/compiler-rt-8.0_pre339409-r1::chromiumos'

BUG=chromium:876533
TEST=equery w sys-libs/compiler-rt shows -r1 ebuild

Change-Id: I8847aea607080d4ec974ce324a235d722cea5791
Reviewed-on: https://chromium-review.googlesource.com/1249601
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Commit-Queue: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>