sys-libs/llvm-libunwind: Add linux-headers as a dependency
llvm-libunwind is one of the primordial packages that needs to be
installed when setting up a board's sysroot. We need to ensure that
the linux headers are installed before we try and build the package.

    In file included from /build/arm64-generic/tmp/portage/sys-libs/llvm-libunwind-16.0_pre475826-r2/work/llvm-libunwind-16.0_pre475826/libunwind/src/UnwindCursor.hpp:35:
    /build/arm64-generic/usr/include/sys/syscall.h:24:10: fatal error: 'asm/unistd.h' file not found
    #include <asm/unistd.h>

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build -k @portage//sys-libs/llvm-libunwind

Change-Id: I14662a74cb633d5f30ac86f18c7f08e074745c2b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4312390
Reviewed-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>