chromeos-base/ec-devutils: Add missing dep
    util/ec_parse_panicinfo.cc:13:10: fatal error: 'libec/ec_panicinfo.h' file not
          found
    #include <libec/ec_panicinfo.h>
             ^~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build  --//bazel/sdk:new-sdk @portage//chromeos-base/ec-devutils

Change-Id: I4e214d4556b044fdde8aed81be8a91a466ad2c6f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4395965
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Shuhei Takahashi <nya@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>