media-libs/cros-camera-sw-privacy-switch-test: Add missing dep
    In file included from ../../../../../../../../../mnt/host/source/src/platform2/camera/gpu/gpu_resources.cc:7:
    In file included from ../../../../../../../../../mnt/host/source/src/platform2/camera/gpu/gpu_resources.h:25:
    ../../../../../../../../../mnt/host/source/src/platform2/camera/gpu/egl/egl_context.h:13:10: fatal error: 'EGL/eglplatform.h' file not found
    #include <EGL/eglplatform.h>
             ^~~~~~~~~~~~~~~~~~~
    1 error generated.

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//media-libs/cros-camera-sw-privacy-switch-test

Change-Id: I03cfb25b1378baa5dc814fe5729dacef968f272d
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4410102
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>