chromeos-base/libbrillo: Update dependency on protofile
Libbrillo needs to know if automatic cleanup on login is required,
added in protofile 0.0.55.

BUG=b:1284559
TEST=On guybrush, without patch, updating libbrillo only fails with:
device_policy_impl.cc:699:23: error: no member named
'has_device_run_automatic_cleanup_on_login' in
'enterprise_management::ChromeDeviceSettingsProto':
...
  if (!device_policy_.has_device_run_automatic_cleanup_on_login())
...

Change-Id: I862842e3f477ab6fc5abc849c6eb6ce855d6b9d2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/3441101
Reviewed-by: Mike Frysinger <vapier@chromium.org>
Reviewed-by: Victor-Gabriel Savu <vsavu@google.com>
Commit-Queue: Gwendal Grignou <gwendal@chromium.org>
Tested-by: Gwendal Grignou <gwendal@chromium.org>