sys-power/dptf: Suppress -Wunsequenced warning
Temporary disable the -Wunsequenced warning to unblock llvm-next
testing.
The new compiler warning causes the following failure:

ESIF_UF/Sources/esif_uf_dsp.c:91:24: error: multiple unsequenced
modifications to 'edpName' [-Werror,-Wunsequenced]
dptf-8.7.10100-r2:         edpName  = (edpName ? ++edpName : filename);

BUG=chromium:1044735
TEST=emerge-eve dptf

Change-Id: I5fe4bf2022ceb611cc6a5ed98028ba30518662c2
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/2015338
Reviewed-by: Jian Cai <jiancai@google.com>
Reviewed-by: Brian Bian <qbbian@gmail.com>
Tested-by: Denis Nikitin <denik@chromium.org>
Commit-Queue: Denis Nikitin <denik@chromium.org>