cryptohome-dev-utils: add missing chaps dep
We seem to have an unexpressed dependency:

cryptohome-dev-utils-0.0.1-r76: /build/chell/tmp/portage/chromeos-base/cryptohome-dev-utils-0.0.1-r76/work/cryptohome-dev-utils-0.0.1/platform2/cryptohome/homedirs.h:21:10: fatal error: 'chaps/token_manager_client.h' file not found
cryptohome-dev-utils-0.0.1-r76: #include <chaps/token_manager_client.h>
cryptohome-dev-utils-0.0.1-r76:          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Take an unconditional dep, similar to the cryptohome ebuild.

BUG=none
TEST=build

Change-Id: I04c108da9175dce87b5cf1452349f8306640444f
Signed-off-by: Brian Norris <briannorris@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/1097591
Reviewed-by: Andrey Pronin <apronin@chromium.org>