chromeos-base/bootlockbox-client: Add missing dep
../../../../../../../../../mnt/host/source/src/platform2/cryptohome/bootlockbox/boot_lockbox_client.cc:12:10: fatal error: 'dbus/cryptohome/dbus-constants.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original-Change-Id: I0192430043900a214dce238d2b70eef0af21d853
Original-Reviewed-on: https://team-review.git.corp.google.com/c/cros-build-tiger/third_party/chromiumos-overlay/+/1624016
Original-Reviewed-by: Shuhei Takahashi <nya@google.com>

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build  --//bazel/sdk:new-sdk @portage//chromeos-base/bootlockbox-client

Change-Id: Id788ec006c0c23b3afc22ecfd1d03f4d51469606
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4338777
Reviewed-by: Shuhei Takahashi <nya@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>