crosvm: Depend on libusb
Without this, a FEATURES=test emerge of crosvm in a clean build
directory fails with:

    error: failed to run custom build command for `usb_util v0.1.0
    (/build/eve/tmp/portage/chromeos-base/crosvm-0.0.1-r297/work/crosvm-0.0.1/usb_util)`
    process didn't exit successfully:
    `/build/eve/tmp/portage/chromeos-base/crosvm-0.0.1-r297/work/debug/build/usb_util-8bb5641490da548b/build-script-build`
    (exit code: 101)
    --- stderr
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
    value: Failure { command: "\"/build/eve/build/bin/pkg-config\"
    \"--libs\" \"--cflags\" \"libusb-1.0\"", output: Output { status:
    ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package libusb-1.0
    was not found in the pkg-config search path.\nPerhaps you should add
    the directory containing `libusb-1.0.pc\'\nto the PKG_CONFIG_PATH
    environment variable\nNo package \'libusb-1.0\' found\n" } }',
    libcore/result.rs:1009:5

The specific wording of `virtual/libusb:1=` is copied from
chromeos-base/ippusb_manager/ippusb_manager-9999.ebuild.

TEST=FEATURES=test emerge-amd64-generic crosvm
TEST=FEATURES=test USE=crosvm-usb emerge-amd64-generic crosvm

Change-Id: I77364ddbc09fc592a833f77d9aa8aa4711d77a75
Reviewed-on: https://chromium-review.googlesource.com/1446505
Commit-Ready: David Tolnay <dtolnay@chromium.org>
Tested-by: David Tolnay <dtolnay@chromium.org>
Reviewed-by: Chirantan Ekbote <chirantan@chromium.org>