cros-kernel2: Install gdb scripts more properly
In some cases when you try to use kgdb to debug a kernel you get:

  PermissionError: [Errno 13] Permission denied:
  '/build/.../usr/lib/debug/boot/scripts/gdb/linux/rbtree.py'

That's because these files are '-rw-r-----' and not '-rw-r--r--'.
Let's add a --chmod to the rsync to fix this.  We'll also use "doins"
for the main script file which had similar problems.

BUG=None
TEST='ls -al'; also gdb no longer yells

Change-Id: I7289a8903fd0f463dc6e779d1c9eadc4ff35b3aa
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/2310478
Tested-by: Douglas Anderson <dianders@chromium.org>
Reviewed-by: Mike Frysinger <vapier@chromium.org>