dev-rust/manatee-client: Fix incorrect dep
Error: Failed to get entries from path.

Caused by:
    0: failed to open config path: No such file or directory (os error 2)
    1: No such file or directory (os error 2)

Stack backtrace:

 * ERROR: dev-rust/manatee-client-9999::arm64-generic failed (install phase):
 *   (no error message)
 *
 * Call stack:
 *               ebuild.sh, line  125:  Called src_install
 *             environment, line 4018:  Called die
 * The specific snippet of code:
 *           tee_app_info_lint -R "${SYSROOT}" -o "${D}/usr/share/manatee/manatee.flex.bin" "${APP_MANIFESTS[@]}" || die;

Needs to be a DEPEND also.

Original-Change-Id: Ide4e8679aff503c8101106398f3e692fd91e58b8
Original-Reviewed-on: https://team-review.git.corp.google.com/c/cros-build-tiger/third_party/chromiumos-overlay/+/1626049
Original-Reviewed-by: Shuhei Takahashi <nya@google.com>
(cherry picked from commit 40feec3b88967c3ae03096c1dee447494fd5dd30)

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build  --//bazel/sdk:new-sdk @portage//virtual/target-os:all

Change-Id: I5148a32a417992f1afb906db14777ecf3f364bad
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4338052
Reviewed-by: Shuhei Takahashi <nya@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>