sys-libs/libunwind: disable stack-protector on armv7a
While testing a glibc 2.35 upgrade locally the following
failure was noticed which turns out is due to an old boot
strapping bug in libgcc because arm uses a global var for
the stack guard canary while x64 and arm64 use TCB vars,
which causes arm glibc builds against libgcc to fail.

There is an open bug report to fix this in GCC:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=102352

I do not know of any bug report opened for libunwind but
according to glibc maintainer Adhemerval, the accepted
workaround is to build arm without the stack protector.

/usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabihf/binutils-bin/2.36.1/ld.bfd.real: /usr/armv7a-cros-linux-gnueabihf/usr/lib/libgcc_eh.a(Unwind-EHABI.cpp.o): in function `_Unwind_VRS_Interpret':
 Unwind-EHABI.cpp:(.text._Unwind_VRS_Interpret+0x35c): undefined reference to `__stack_chk_guard'
 /usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabihf/binutils-bin/2.36.1/ld.bfd.real: Unwind-EHABI.cpp:(.text._Unwind_VRS_Interpret+0x360): undefined reference to `__stack_chk_guard'
 /usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabihf/binutils-bin/2.36.1/ld.bfd.real: /usr/armv7a-cros-linux-gnueabihf/usr/lib/libgcc_eh.a(Unwind-EHABI.cpp.o): in function `_Unwind_VRS_Pop':
 Unwind-EHABI.cpp:(.text._Unwind_VRS_Pop+0x13c): undefined reference to `__stack_chk_guard'
 /usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabihf/binutils-bin/2.36.1/ld.bfd.real: Unwind-EHABI.cpp:(.text._Unwind_VRS_Pop+0x140): undefined reference to `__stack_chk_guard'
 /usr/x86_64-pc-linux-gnu/armv7a-cros-linux-gnueabihf/binutils-bin/2.36.1/ld.bfd.real: /usr/armv7a-cros-linux-gnueabihf/usr/lib/libgcc_eh.a(Unwind-EHABI.cpp.o): in function `(anonymous namespace)::unwindOneFrame(unsigned int, _Unwind_Control_Block*, _Unwind_Context*)':

BUG=b:235960683
TEST=Local builds against glibc 2.35.

Change-Id: I40dd03cbc723125e82d040cff433d98009aa206f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/3720699
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Commit-Queue: Manoj Gupta <manojgupta@chromium.org>
Tested-by: Manoj Gupta <manojgupta@chromium.org>