app-benchmarks/xfstests: add missing dependencies
Adding sys-apps/util-linux for missing libuuid (first error):
checking for uuid_compare... no
checking for uuid_compare in -luuid... no
FATAL ERROR: could not find a valid UUID library.

Adding sys-fs/xfsprogs for missing headers (second error):
checking for xfs/xfs.h... no
FATAL ERROR: cannot find a valid <xfs/xfs.h> header file.

BUG=b:273158812
TEST=BOARD=amd64-generic bazel build @portage//app-benchmarks/xfstests

Original-Change-Id: I8d6cd7c5792230020b42b1ec29b688e391f7d5a3
Original-Reviewed-on: https://team-review.git.corp.google.com/c/cros-build-tiger/third_party/chromiumos-overlay/+/1789894
Original-Reviewed-by: Shuhei Takahashi <nya@google.com>
(cherry picked from commit f05c60b9ec19598ee4f13479a75e1dc95e1c8336)

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//app-benchmarks/xfstests

Change-Id: I534863f055b56c424377fde2a937cc211628b7ba
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4410044
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>