sys-libs/libcxx: Add linux headers as a dependency
libcxx is one of the primordial packages that needs to be
installed when setting up a board's sysroot. We need to ensure that
the linux headers are installed before we try and build the package.

    In file included from /build/arm64-generic/tmp/portage/sys-libs/libcxx-16.0_pre475826-r2/work/libcxx-16.0_pre475826/libcxx/src/filesystem/directory_iterator.cpp:11:
    In file included from include/c++/v1/errno.h:31:
    In file included from /build/arm64-generic/usr/include/errno.h:28:
    /build/arm64-generic/usr/include/bits/errno.h:26:11: fatal error: 'linux/errno.h' file not found
    # include <linux/errno.h>
              ^~~~~~~~~~~~~~~
    1 error generated.

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build -k @portage//sys-libs/libcxx

Change-Id: I2c19c6bbc7b948559a7f255d48dd10538704cdaf
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4312391
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>