python-uinput: make cros_type_keys.py compatible with Python 3
Python 3 now seems to be the default interpreter in Chromium OS, and
running this script with it results in the following error message:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/uinput/cros_type_keys.py", line 7, in <module>
    import cros_keys
ModuleNotFoundError: No module named 'cros_keys'

Twiddle the import line a bit so it now works with both versions.

BUG=chromium:1037993
TEST=python3 -m uinput.cros_type_keys $'some_input\n'
TEST=python2 -m uinput.cros_type_keys $'some_input\n'

Change-Id: I25ddeffeb89e7b2ae6819c74d64f4be51b80d017
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/1982940
Tested-by: Alexandre Courbot <acourbot@chromium.org>
Reviewed-by: Nicolas Boichat <drinkcat@chromium.org>
Commit-Queue: Alexandre Courbot <acourbot@chromium.org>