chromeos-base/shill-dbus-client: Add missing dep
In file included from ../../../../../../../../../mnt/host/source/src/platform2/shill/dbus/client/client.cc:5:
../../../../../../../../../mnt/host/source/src/platform2/shill/dbus/client/client.h:22:10: fatal error: 'chromeos/dbus/service_constants.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Original-Change-Id: I4ac9a52486ce43b02cb266636ee0af0992763da0
Original-Reviewed-on: https://team-review.git.corp.google.com/c/cros-build-tiger/third_party/chromiumos-overlay/+/1624014
Original-Reviewed-by: Shuhei Takahashi <nya@google.com>
(cherry picked from commit 1498577524cb827bee8fbead5df7b0f217d902c5)

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build  --//bazel/sdk:new-sdk @portage//virtual/target-os:all

Change-Id: Ibcd0e75ec2fa02d00f7bf499bbba2dcf6e9bee0f
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4338776
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Steven Bennetts <stevenjb@chromium.org>