chromeos-base/oobe_config: Add missing dep
    In file included from ../../../../../../../../../mnt/host/source/src/platform2/oobe_config/oobe_config_restore_service.cc:11:
    In file included from ../../../../../../../../../mnt/host/source/src/platform2/libhwsec/factory/factory.h:14:
    In file included from ../../../../../../../../../mnt/host/source/src/platform2/libhwsec/frontend/cryptohome/frontend.h:15:
    ../../../../../../../../../mnt/host/source/src/platform2/libhwsec/backend/signature_sealing.h:16:10: fatal error: 'libhwsec/structures/signature_sealed_data.h' file not found
    #include "libhwsec/structures/signature_sealed_data.h"
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build  --//bazel/sdk:new-sdk @portage//virtual/chromeos-base/oobe_config

Change-Id: Id65f99dd5ca23a5c4a85f45d587a91a496230273
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4364253
Reviewed-by: Shuhei Takahashi <nya@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>