chromeos-base/ec-devutils: Add missing dep
    /build/arm64-generic/usr/include/libchrome/testing/gtest/include/gtest/gtest_prod.h:1:10: fatal error:
          'gtest/gtest_prod.h' file not found
    #include <gtest/gtest_prod.h>
             ^~~~~~~~~~~~~~~~~~~~
    1 error generated.
    make: *** [Makefile.rules:693: build/host/util/ectool] Error 1

BUG=b:262460834, b:274791539
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//chromeos-base/ec-devutils

Change-Id: Ia186c33ed4b4628e107d723ca0b9a0e833b3c7de
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4395966
Reviewed-by: Shuhei Takahashi <nya@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>