chromeos-base/ec-utils: Add missing dep
gtest is required because libec includes a libchrome header that
requires gtest to be installed when building.

    In file included from util/ectool.cc:39:
    In file included from /build/arm64-generic/usr/include/libec/add_entropy_command.h:9:
    In file included from /build/arm64-generic/usr/include/libec/ec_command_async.h:10:
    In file included from /build/arm64-generic/usr/include/libchrome/base/threading/thread.h:15:
    In file included from /build/arm64-generic/usr/include/libchrome/base/functional/callback.h:17:
    In file included from /build/arm64-generic/usr/include/libchrome/base/functional/bind.h:14:
    In file included from /build/arm64-generic/usr/include/libchrome/base/functional/bind_internal.h:21:
    In file included from /build/arm64-generic/usr/include/libchrome/base/functional/callback_internal.h:16:
    In file included from /build/arm64-generic/usr/include/libchrome/base/memory/ref_counted.h:19:
    In file included from /build/arm64-generic/usr/include/libchrome/base/gtest_prod_util.h:8:
    /build/arm64-generic/usr/include/libchrome/testing/gtest/include/gtest/gtest_prod.h:1:10: fatal error:
          'gtest/gtest_prod.h' file not found
    #include <gtest/gtest_prod.h>
             ^~~~~~~~~~~~~~~~~~~~
    1 error generated.

BUG=b:262460834, b:274791539
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//chromeos-base/ec-utils

Change-Id: I2ed010a827e4bf79c46b5c041ee22a052661792e
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4369729
Tested-by: Raul Rangel <rrangel@chromium.org>
Reviewed-by: Alex Klein <saklein@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>