chromeos-base/aosp-frameworks-ml-nn-vts: missing dependency
Adding dev-libs/libtextclassifier to fix:
../../../../../../../tmp/portage/chromeos-base/aosp-frameworks-ml-nn-vts-9999/work/aosp-frameworks-ml-nn-vts-9999/platform2/aosp/frameworks/ml/common/operations/LSHProjectionExecution.cpp:19:10: fatal error: 'utils/hash/farmhash.h' file not found
         ^~~~~~~~~~~~~~~~~~~~~~~

BUG=b:273158812
TEST=BOARD=amd64-generic bazel build @portage//chromeos-base/aosp-frameworks-ml-nn-vts

Original-Change-Id: I0e79dccf2081cce1ff31a0075cdcfdb69e6b5c83
Original-Reviewed-on: https://team-review.git.corp.google.com/c/cros-build-tiger/third_party/chromiumos-overlay/+/1789899
Original-Reviewed-by: Shuhei Takahashi <nya@google.com>
(cherry picked from commit 9d87b634f9bdd258402926159b44553dce5eca45)

BUG=b:262460834
TEST=BOARD=arm64-generic bazel build --//bazel/sdk:new-sdk @portage//chromeos-base/aosp-frameworks-ml-nn-vts

Change-Id: I7da09f74a9223f88d3076006a3d88ed13c7d5e7c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/4410045
Reviewed-by: Alex Klein <saklein@chromium.org>
Tested-by: Raul Rangel <rrangel@chromium.org>
Commit-Queue: Raul Rangel <rrangel@chromium.org>