Check the value of Board ID before trying to write SN Bits
If we don't check and Board ID is already set, the command to write
SN Bits will fail with a somewhat cryptic "Error 7 while sending vendor
command" message. Instead, we provide a user-friendly error message
explaining that we cannot set SN Bits due to Board ID being set.

Example of using the command with Board ID already set:

> /usr/share/cros/cr50-set-sn-bits.sh
ERROR: Cannot set SN Bits since Board ID is already set.
> echo $?
4
>

BUG=chromium:1058432
TEST=run the script

Change-Id: I76c5a23b353315dc059339d8689ae3b0d404ddd3
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/2088080
Tested-by: Yves Arrouye <drcrash@chromium.org>
Commit-Queue: Yves Arrouye <drcrash@chromium.org>
Reviewed-by: Stimim Chen <stimim@chromium.org>
Reviewed-by: Benjamin Gordon <bmgordon@chromium.org>