diag: add sanitizer support
This package fails to build for trogdor with profile=asan; we get errors
like:

ld.lld: error: /build/trogdor/usr/lib/libqrtr.so: undefined reference to
__asan_report_store1

Looks like this is because we're not passing `-fsanitize=address` to
clang.

BUG=b:205180351
TEST=emerge-trogdor net-misc/diag

Change-Id: If8c2139d22ab6f97f5a1f782ba9347c6f09643a6
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/overlays/chromiumos-overlay/+/3265814
Reviewed-by: Manoj Gupta <manojgupta@chromium.org>
Commit-Queue: George Burgess <gbiv@chromium.org>
Tested-by: George Burgess <gbiv@chromium.org>